---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: system
  name: stateful-auto-scaler-role
rules:
- apiGroups:
  - scaling.example.com
  resources:
  - scalingpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.example.com
  resources:
  - scalingpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - scaling.example.com
  resources:
  - scalingpolicies/status
  verbs:
  - get
  - patch
  - update
