apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: stateful-auto-scaler
    app.kubernetes.io/managed-by: kustomize
  name: stateful-auto-scaler-rolebinding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stateful-auto-scaler-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
