apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: stateful-auto-scaler
    app.kubernetes.io/managed-by: kustomize
  name: stateful-auto-scaler-rolebinding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scalingpolicy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
