apiVersion: scaling.example.com/v1alpha1
kind: ScalingPolicy
metadata:
  name: test-scaling-policy
spec:
  minReplicas: 2
  maxReplicas: 10
  cpuThreshold: 75
  memoryThreshold: 80
  metricSource: "prometheus"
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70