apiVersion: scaling.example.com/v1alpha1
kind: ScalingPolicy
metadata:
  labels:
    app.kubernetes.io/name: stateful-auto-scaler
    app.kubernetes.io/managed-by: kustomize
  name: scalingpolicy-sample
spec:
  # TODO(user): Add fields here
